---
# ArgoCD Application Configuration
acm_argocd_app_name: "acm-hub"
acm_argocd_namespace: "openshift-gitops"
acm_argocd_project: "default"
acm_argocd_sync_policy: "Automatic"

# Git Repository Configuration
acm_git_repo_url: "https://github.com/SkylarScaling/gitops-install-acm.git"
acm_git_repo_path: "acm"
acm_git_repo_revision: "main"

# Target Namespace for ACM deployment
acm_target_namespace: "open-cluster-management"