---
# The update channel to subscribe to (e.g., gitops-1.10, gitops-1.11, latest)
gitops_operator_channel: "gitops-1.19"

# The name of the CatalogSource
gitops_operator_source: "redhat-operators"

# The namespace of the CatalogSource
gitops_operator_source_namespace: "openshift-marketplace"

# The namespace to install the operator into
# 'openshift-operators' is the standard global namespace for operators
gitops_operator_namespace: "openshift-operators"

# Set to true if you want to wait for the ArgoCD instance to be ready after install
wait_for_operator_ready: true